# Generated by Django 3.2.16 on 2024-11-08 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='description')),
                ('doc_date', models.DateTimeField(help_text='Дата оригинального документа', verbose_name='Дата оригинального документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации')),
            ],
            options={
                'verbose_name': 'документы',
                'verbose_name_plural': 'Документы',
                'ordering': ('-doc_date',),
            },
        ),
        migrations.CreateModel(
            name='DocumentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='document_images', verbose_name='Фото')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='archive.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
